spring:
  application:
    name: saldo

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true

json:
  server:
    url: "http://localhost:3000"

logging:
  level:
    root: INFO
    github.com.claudevan.saldo: DEBUG