spring:
  application:
    name: saldo

server:
  port: 8080

json:
  server:
    url: "http://localhost:3000"

logging:
  level:
    root: INFO
    github.com.claudevan.saldo: DEBUG
    org.springframework.actuator: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'  # ou 'metrics' se quiser expor apenas métricas
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
